# Numpy Metodları

In [2]:
import numpy as np

### arange

Belli bir aralıkta belli adımda bir numpy dizisi oluşturur.

In [3]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### zeros

İçerisinde istenilen sayıda 0 bulunduran bir dizi oluşturur.

In [5]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones

İçerisinde istenilen sayıda 1 bulunduran bir dizi oluşturur.

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### linspace

Belirli değerler arasında eşit aralıklarda istenilen sayıda değer içeren dizi oluşturur.

In [9]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### eye

Birim matris oluşturur.

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random

Rastgele bazı değerler oluşturur.
* randn : ortalaması 0 standart sapması 1 olan normal dağılım veri kümesinden rastgele değerler seçer.
* randint : iki değer arasında istenilen sayıda int rastgele değerlere sahip dizi oluşturur.
* random : 0 ve 1 arasında rastgele değerler üretir.

In [11]:
np.random.randn(4)

array([-0.21418066, -0.47717955, -0.53004338, -0.17973043])

In [12]:
np.random.randn(5,5)

array([[-0.18278392, -1.23096288, -0.65451735,  0.30079422,  0.5533987 ],
       [-0.2625869 , -1.51138966,  0.13589253, -0.64269257,  0.28789785],
       [-0.03971293,  1.95271207,  0.38897614,  1.51997765, -0.31471359],
       [-1.3290244 ,  2.42703098,  1.96784896, -0.8568163 , -0.12661192],
       [ 1.02911988,  0.08725159, -0.09529254, -0.39886906, -0.21436703]])

In [13]:
np.random.randint(1,50)

31

In [14]:
np.random.randint(50, 100, 5)

array([70, 94, 71, 87, 68])

In [15]:
np.random.randint(50, 100, size=(2,4))

array([[52, 74, 63, 52],
       [77, 74, 86, 61]])

In [16]:
np.random.random(10)

array([0.75331275, 0.93932937, 0.69576985, 0.76534122, 0.94508124,
       0.6439356 , 0.78586571, 0.19313387, 0.36021401, 0.24387781])

# Numpy Array Metodları

In [17]:
import numpy as np

In [18]:
sequenceArray = np.arange(0,30)
randomArray = np.random.randint(0,100,20)

print(sequenceArray)
print(randomArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[29 62 61  4 53 17 48 32 29 74  2 79  0 68  8 47 67 12 16 95]


### reshape

Dizinin boyutlarını istenilen değerlere göre günceller.

In [19]:
sequenceArray.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### max & min

In [20]:
randomArray.max()

95

In [21]:
randomArray.min()

0

### argmax & argmin

Dizideki min ve max değerlerin hangi indekste bulunduğunu döndürür.

In [22]:
randomArray.argmax()

19

In [23]:
randomArray.argmin()

12

### shape

Dizinin satır - sütun değerlerini verir. Attribute'dur.

In [24]:
randomArray.shape

(20,)

### ndim
Dizinin boyutunu verir.

In [25]:
randomArray.ndim

1

### ravel

n boyutlu diziyi düzleştirme yöntemi ile tek boyuta indirger.

In [26]:
randomArray.ravel()

array([29, 62, 61,  4, 53, 17, 48, 32, 29, 74,  2, 79,  0, 68,  8, 47, 67,
       12, 16, 95])