# Numpy Array (Vektör 1D) İndeks İşlemleri

In [1]:
import numpy as np

In [3]:
myArray = np.arange(10)
myArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Slicing

Listelerle kullanımı benzerdir. Orada kullanılan slicing yöntemlerini kullanabilirsiniz.

In [4]:
myArray[5]

5

In [5]:
myArray[3:6]

array([3, 4, 5])

In [7]:
myArray[3:6] = -1
myArray

array([ 0,  1,  2, -1, -1, -1,  6,  7,  8,  9])

**Not:** Eğer dizinizi başka bir değişkene eşitlerseniz ve bu değişkendeki dizi değerlerini değiştiriseniz ana dizideki değerlerde değişir. Bunu engellemek için ana dizinizin **copy()** metodu ile kopyasını oluştururarak işlem yapınız.

In [8]:
exampleArray = np.arange(10)
exampleArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
notCopyArray = exampleArray[5:9]
notCopyArray

array([5, 6, 7, 8])

In [12]:
notCopyArray[:] = 100
print(notCopyArray)
print(exampleArray)

[100 100 100 100]
[  0   1   2   3   4 100 100 100 100   9]


In [13]:
exampleArray = np.arange(10)
exampleArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
copyArray = exampleArray.copy()
copyArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
copyArray[4:8] = 100
print(copyArray)
print(exampleArray)

[  0   1   2   3 100 100 100 100   8   9]
[0 1 2 3 4 5 6 7 8 9]


# Numpy Matris (2D) İndeks İşlemleri

In [1]:
import numpy as np

In [5]:
liste = [[10,20,30],[40,50,60],[70,80,90]]
matrix = np.array(liste)
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### Satır Değerlerini Alma

In [6]:
matrix[0]

array([10, 20, 30])

#### Sütun Değerlerini Alma

In [15]:
matrix[:,2]

array([30, 60, 90])

#### Belli Bir Değeri Alma

In [13]:
matrix[1][2]

60

In [14]:
matrix[1,2]

60

#### Liste ile İndeksleme

In [16]:
matrix[[0,2]]

array([[10, 20, 30],
       [70, 80, 90]])

In [17]:
matrix[[0,2],[1]]

array([20, 80])