# Numpy Operasyonlar

In [1]:
import numpy as np

In [2]:
randomArray = np.random.randint(1,100,20)
randomArray

array([48, 68, 86, 66, 54, 91, 14, 31, 91, 20, 48, 51, 70, 43, 38, 81,  2,
       30, 91, 74])

#### Bir Değerden Büyük veya Küçük Değerleri Bulma

In [8]:
randomArray[randomArray > 50]

array([68, 86, 66, 54, 91, 91, 51, 70, 81, 91, 74])

#### Matematiksel İşlemler

In [9]:
np.arange(0,20) + np.arange(0,20)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [10]:
np.arange(0,20) - np.arange(0,20)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.arange(0,20) * np.arange(0,20)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [12]:
np.arange(0,20) / np.arange(0,20)

C:\Users\enes\AppData\Local\Temp\ipykernel_4004\924064255.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.arange(0,20) / np.arange(0,20)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Dizideki Unique Değerleri Bulma

In [13]:
np.unique(np.array([1,1,5,5,6,7,3,6]))

array([1, 3, 5, 6, 7])

#### Değerleri Yuvarlama

In [15]:
np.round(np.random.random(5), 2)

array([0.61, 0.84, 0.32, 0.38, 0.08])

#### Mutlak Değer Alma

In [17]:
noneAbsArray = np.random.randint(-5,5,(3,4))
print(noneAbsArray)
np.abs(noneAbsArray)

[[ 0  3  3 -5]
 [ 4 -2  2  3]
 [ 2  4  2 -3]]


array([[0, 3, 3, 5],
       [4, 2, 2, 3],
       [2, 4, 2, 3]])

#### Karekök Alma

In [20]:
myArray = np.random.randint(0,5,(3,4))
print(myArray)
np.sqrt(myArray)

[[2 2 1 4]
 [4 3 0 2]
 [3 0 4 3]]


array([[1.41421356, 1.41421356, 1.        , 2.        ],
       [2.        , 1.73205081, 0.        , 1.41421356],
       [1.73205081, 0.        , 2.        , 1.73205081]])

#### Karelerini Alma

In [22]:
squareArray = np.array([[2,5,6],[-1,5,8]])
print(squareArray)
np.square(squareArray)

[[ 2  5  6]
 [-1  5  8]]


array([[ 4, 25, 36],
       [ 1, 25, 64]])

# Matris İşlemleri

Vektör işlemleri için kullanılan metodlar matrisler içinde kullanılmaktadır.

In [23]:
import numpy as np

#### İki Matrisi Toplama

In [24]:
A = np.array([[2, 4], [5, -6]])
print(A)
B = np.array([[9, -3], [3, 6]])
print(B)
C = A + B 
print(C)

[[ 2  4]
 [ 5 -6]]
[[ 9 -3]
 [ 3  6]]
[[11  1]
 [ 8  0]]


#### İki Matrisi Çıkarma

In [25]:
A = np.array([[2, 4], [5, -6]])
print(A)
B = np.array([[9, -3], [3, 6]])
print(B)
C = A - B 
print(C)

[[ 2  4]
 [ 5 -6]]
[[ 9 -3]
 [ 3  6]]
[[ -7   7]
 [  2 -12]]


#### Elemansal Çarpım

In [26]:
A = np.array([[2, 4], [5, -6]])
print(A)
B = np.array([[9, -3], [3, 6]])
print(B)
C = A * B 
print(C)

[[ 2  4]
 [ 5 -6]]
[[ 9 -3]
 [ 3  6]]
[[ 18 -12]
 [ 15 -36]]


#### Matris Çarpımı

In [27]:
A = np.array([[3, 6, 7], [5, -3, 0]])
print(A)
B = np.array([[1, 1], [2, 1], [3, -3]])
print(B)
C = A.dot(B)
print(C)

[[ 3  6  7]
 [ 5 -3  0]]
[[ 1  1]
 [ 2  1]
 [ 3 -3]]
[[ 36 -12]
 [ -1   2]]


#### Matrisin Transpozu

In [28]:
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A)
print(A.transpose())

[[ 1  1]
 [ 2  1]
 [ 3 -3]]
[[ 1  2  3]
 [ 1  1 -3]]
